-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "WhiteSur-cursors")
hl.env("XCURSOR_SIZE", "24")

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1024x768@70.07Hz",
    position = "1920x1080",
    scale = 1,
    bitdepth = 10,
    vrr = 0,
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.01Hz",
    position = "0x768",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
})
