-- Generated by nwg-displays on 2026-09-01 at 17:08:00. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "1024x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1024x768@75.03",
    position = "0x312",
    scale = 1,
    bitdepth = 10,
    vrr = 0
})
