-- Generated by nwg-displays on 2026-08-17 at 10:56:49. Do not edit manually.

hl.workspace_rule({
	workspace = "6",
	monitor = "HDMI-A-1",
})
hl.workspace_rule({
	workspace = "5",
	monitor = "HDMI-A-1",
})
hl.workspace_rule({
	workspace = "4",
	monitor = "HDMI-A-1",
	default = true,
})
hl.workspace_rule({
	workspace = "3",
	monitor = "eDP-1",
})
hl.workspace_rule({
	workspace = "2",
	monitor = "eDP-1",
})
hl.workspace_rule({
	workspace = "1",
	monitor = "eDP-1",
	default = true,
})
